#!/usr/bin/python3
from sys import argv

def factorize(key: int) -> None:
    '''
        Factorize the given prime key
    '''
    for i in range(2, key):
        if key % i == 0:
            print(f'{key}={key//i}*{i}')
            break
    return

def Main() -> None:
    '''
        Main program handler
    '''
    if len(argv) == 2:
        with open(str(argv[1]), 'r') as f:
            keys = f.readlines()
            for key in keys:
                factorize(int(key.strip()))
        return
    print('Usage RSA_factoring.py <file>')
    return

if __name__ == '__main__':
    Main()
